# Generated by Django 5.2.3 on 2025-06-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresses',
            new_name='Address',
        ),
    ]
